### ISSUE TITLE
Revise README

### ISSUE THREAD

**Issue by ghost** [elastos/Elastos.Trinity#16]
Main goal is to simplify/clarify the README (an entry-point for code-level interested developers).

- [x] move ROADMAP out (#18, #19)
- [x] #22 do 2 or 3 iterations 
- [ ] #21 Clariy Branding
- [ ] #17 Point to daily/beta releases

**Comment by BenjaminPiette** [comment]
Agree with you, we have to improve the roadmap this is in my mind since a while. Though there are other priorities for now unfortunately. Thank you for reporting this, we will take a look as soon as we can.

**Comment by lazaridiscom** [comment]
I can give it a try.

(It looks you're a bit overworked?)

**Comment by lazaridiscom** [comment]
used the github UI, so 2 PRs: #18, #19

(more will follow, once they're merged)

**Comment by BenjaminPiette** [comment]
Thanks for this!
